language: ruby

rvm:
  - 2.3.1

env:
  - DB=sqlite

script:
  - export TZ=America/Mexico_City
  - date
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - cd spec/dummy
  - cd ../../
  - bundle exec rspec spec --color